spring:
  application:
    name: BoardApp
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
#    url: jdbc:h2:~/skboard
    url: jdbc:h2:tcp://localhost/~/skboard
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌

logging.level:
  org.hibernate.SQL: debug